General improvements
pep8speaks-org/pep8speaks pull request #19
Opened 2017-02-21 04:24 UTC by ashwch

- Grouped imports properly, plus fixed their ordering.
- Not creating files wherever possible.
- Looping over dict without `.keys()` and using `.items()` wherever it makes sense to use it.
- Instead of concatenating strings using `+=` we are now collection them in a list and joining them at the end. Not only this is fast, it makes code look a bit clean as well.

2017-02-21 04:24 UTC, pep8speaks commented
Hello @ashwch! Thanks for submitting the PR.

 - There are no PEP8 issues in the file [`app.py`](https://github.com/ashwch/pep8speaks/blob/36f8c9dd267fa5f723fd22198b52a7a9f95366cc/app.py) !

 - There are no PEP8 issues in the file [`pep8speaks/handlers.py`](https://github.com/ashwch/pep8speaks/blob/36f8c9dd267fa5f723fd22198b52a7a9f95366cc/pep8speaks/handlers.py) !

 - There are no PEP8 issues in the file [`pep8speaks/helpers.py`](https://github.com/ashwch/pep8speaks/blob/36f8c9dd267fa5f723fd22198b52a7a9f95366cc/pep8speaks/helpers.py) !

2017-02-25 07:28 UTC, ashwch commented
@OrkoHunter Does this look good to you?

2017-02-25 08:04 UTC, OrkoHunter requested changes
All of this looks really good. I tested the branch and with few requested changes this is good to go. Thanks a lot!

2017-02-25 08:04 UTC, OrkoHunter commented on pep8speaks/helpers.py
> +    patch = unidiff.PatchSet(r.text.splitlines(), encoding='utf-8')
Please remove `encoding='utf-8'` as it causes an error with the line.
```
127.0.0.1 - - [25/Feb/2017 13:06:27] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hunter/workspace/pep8speaks/app.py", line 46, in main
    return handlers.handle_pull_request(request)
  File "/home/hunter/workspace/pep8speaks/pep8speaks/handlers.py", line 52, in handle_pull_request
    helpers.run_pycodestyle(data, config)
  File "/home/hunter/workspace/pep8speaks/pep8speaks/helpers.py", line 171, in run_pycodestyle
    patch = unidiff.PatchSet(r.text.splitlines(), encoding='utf-8')
  File "/usr/local/lib/python3.5/dist-packages/unidiff/patch.py", line 278, in __init__
    self._parse(data, encoding=encoding)
  File "/usr/local/lib/python3.5/dist-packages/unidiff/patch.py", line 292, in _parse
    line = line.decode(encoding)
AttributeError: 'str' object has no attribute 'decode'
```

2017-02-25 08:04 UTC, OrkoHunter commented on pep8speaks/helpers.py
> +                comment_body.append("> {0}".format(error_string))
This needs to be
```
comment_body.append("\n> {0}".format(error_string))
```
because of the changes above.

2017-02-25 08:04 UTC, OrkoHunter commented on pep8speaks/helpers.py
> +    patch = unidiff.PatchSet(r.text.splitlines(), encoding='utf-8')
Please remove encoding from here, too.

2017-02-25 08:04 UTC, OrkoHunter commented on pep8speaks/helpers.py
> +    patch = unidiff.PatchSet(r.text.splitlines(), encoding='utf-8')
Same goes for this line.

2017-02-25 10:32 UTC, ashwch commented on pep8speaks/helpers.py
> +    patch = unidiff.PatchSet(r.text.splitlines(), encoding='utf-8')
I have changed it to split on `.content`(bytes) rather than `.text`, and we will pass the encoding used by `requests` to `PatchSet` method.

2017-02-25 10:33 UTC, ashwch commented on pep8speaks/helpers.py
> +    patch = unidiff.PatchSet(r.text.splitlines(), encoding='utf-8')
https://github.com/OrkoHunter/pep8speaks/pull/19/commits/0c9c656562a14f9458ffc16078cb4d230f33acca does something similar as well.

2017-02-25 10:38 UTC, OrkoHunter approved these changes

2017-02-25 10:38 UTC, OrkoHunter commented
@ashwch This works well ! Merging this now.

2017-02-25 10:38 UTC, merged

2017-02-25 10:49 UTC, ashwch commented
@OrkoHunter Thanks for the merge. I missed one thing, add it in a separated PR: https://github.com/OrkoHunter/pep8speaks/pull/22