Fix/deps
pep8speaks-org/pep8speaks pull request #220
Opened 2023-12-09 23:29 UTC by Mr-Sunglasses

fixed: #196

2023-12-09 23:30 UTC, Mr-Sunglasses commented
@tushar5526 I've checked locally, the update version of deps does not break anything.

2023-12-10 19:16 UTC, tushar5526 commented
Have you tested the docker build as well? Which Python version are you using?

2023-12-25 21:44 UTC, Mr-Sunglasses commented
@tushar5526 I've tested it for python `[3.9, 3.10, 3.11]`

2023-12-28 10:21 UTC, tushar5526 commented
@Mr-Sunglasses let's not use `>=` as it might install a dependency with a change in the major version. Can you replace them with `~=` to fix the major version?

2023-12-28 10:21 UTC, tushar5526 requested changes
Replace `>=` to `~=`

2024-02-22 06:07 UTC, Mr-Sunglasses commented
@tushar5526 I've done the necessary changes, I think now we're ready to merge 🧜🏻‍♀️

2024-04-11 22:49 UTC, merged